### ISSUE TITLE
Direkter Link auf Cafeteria West

### ISSUE THREAD

**Issue by dervomsee** [seder/mensaplan-web-interface#1]
Hallo,
schick sieht die neue Seite aus!
Aber es fehlt mir die Möglichkeit einen direkten Link auf das aktuelle Essen der Cafeteria West zu speichern. 
Der Link könnte wie folgt (ohne Datum) aussehen: http://www.uni-ulm.de/mensaplan/beta/#West
Es wäre schön wenn dieser Link auf das aktuelle Datum verweisen würde.
Grüße

**Comment by seder** [comment]
Vielen Dank fürs Feedback! Klingt nach einer guten Idee, ich werde es mir heute abend mal anschauen.

**Comment by seder** [comment]
So, funktioniert jetzt. Habe dabei gleich noch ein paar andere Sachen geaddet (siehe readme.md).
