### ISSUE TITLE
Links vom Studentenwerk wurden geändert

### ISSUE THREAD

**Issue by seanschneeweiss** [seder/mensaplan-web-interface#3]
Die Links zu den PDFs des Studentenwerks wurden geändert (wegen Relaunch). Deswegen funktioniert der PDF Parser nicht mehr.

**Comment by seder** [comment]
Das ist zwar richtig aber das falsche Projekt für das Issue, deswegen geschlossen (dieses Repo ist nur das Webinterface, das immernoch funktionieren würde wenn denn die Daten da wären, der Parser ist unter github.com/seder/mensaplan-parser zu finden). Vielen Dank trotzdem für den Bugreport.
