### ISSUE TITLE
Wichtige Ernährungsinformationen fehlen im web-interface.

### ISSUE THREAD

**Issue by metaknight2405** [seder/mensaplan-web-interface#4]
Lädt man den Speiseplan im Studierendenwerk runter sind Icons zu Vegatarischen und Veganen Speisen abgebildet.
Auf dem Web-interface kann man vegetarische und vegane Speisen nicht unterscheiden, was es für manche Leute unbrauchbar macht.

LG

**Comment by seder** [comment]
Hallo metaknight,

das Web-Interface greift auf die Daten vom mensaplan-parser zurück ( https://github.com/seder/mensaplan-parser ). Dieser parst die PDF-Dateien vom Studierendenwerk. Leider ist die Info vegetarisch/vegan in den PDFs nur als Bilddatei drin. Um also die Daten zu parsen müsste ich die Position der Bilder bestimmen und dem richtigen Gericht zuordnen, erkennen ob die Bilder dem Vegetarisch / Vegan Symbol ähneln (leider sind die Bilder nicht immer gleich, sondern verzerrt und mal größer mal kleiner. Wie man dem jetzigen Plan schon entnehmen kann, ist das alles sehr fehleranfällig, darauf verlassen kann man sich als Vegetarier / Veganer also ohnehin nicht.

Ich bin aber auch mit dem Studierendenwerk im Gespräch, es wird zur Zeit an einer offiziellen API gearbeitet, die nicht nur diese sondern viel mehr Infos direkt enthalten wird. Es sollte dann möglich sein, direkt Filter anzugeben, mit denen nur das angezeigt wird, was man auch essen kann / will. Dies betrifft nicht nur vegetarisch / vegan sondern wahrscheinlich auch Halal und Allergene. Ich warte die API ab, dann wird das auch aufgenommen.

Viele Grüße
